### ISSUE TITLE
We don't delete the info dir when we repeat a download

### ISSUE THREAD

**Issue by brilliant-ember** [brilliant-ember/YouTube-Channel-Downloader#6]
We need to delete the file if it already exists

```
02/11/2021 08:01:45 - Will move the info dir to inside the channel dir now
02/11/2021 08:01:45 - Error("Destination path 'youtube_backup/GreatScott!/info' already exists")
Traceback (most recent call last):
  File "/Volumes/storage/youtube/source_code/Downloader.py", line 105, in move_info_to_inside_the_channel
    shutil.move(self.info_dir, self.channel_path)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 804, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'youtube_backup/GreatScott!/info' already exists
02/11/2021 08:01:45 - Goodbye and God bless you!
mo@mos source_code %
```

**Comment by brilliant-ember** [comment]
related to https://github.com/brilliant-ember/YouTube-Channel-Downloader/issues/3
